/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/reactions/{item}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get reaction counts for an item */
        get: operations["ReactionsController_getReactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reactions/{item}/{reactionType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a reaction to an item */
        post: operations["ReactionsController_addReaction"];
        /** Remove a reaction from an item */
        delete: operations["ReactionsController_removeReaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ReactionTypeResponseDto: {
            /**
             * @description Number of reactions
             * @example 5
             */
            count: number;
            /**
             * @description Whether the current user has given this reaction
             * @example true
             */
            hasReacted?: boolean;
        };
        ReactionResponseDto: {
            /** @description LOVE reactions information */
            LOVE: components["schemas"]["ReactionTypeResponseDto"];
            /** @description FIRE reactions information */
            FIRE: components["schemas"]["ReactionTypeResponseDto"];
            /** @description ADMIRE reactions information */
            ADMIRE: components["schemas"]["ReactionTypeResponseDto"];
            /** @description CLAP reactions information */
            CLAP: components["schemas"]["ReactionTypeResponseDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ReactionsController_getReactions: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional user ID to check if user has reacted */
                userId?: string;
            };
            path: {
                /** @description Unique identifier of the item */
                item: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The reaction counts for the item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReactionResponseDto"];
                };
            };
        };
    };
    ReactionsController_addReaction: {
        parameters: {
            query?: never;
            header: {
                /** @description User ID required to add a reaction */
                userId: string;
            };
            path: {
                /** @description Unique identifier of the item */
                item: string;
                /** @description Type of reaction to add */
                reactionType: "LOVE" | "FIRE" | "ADMIRE" | "CLAP";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The updated reaction counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReactionResponseDto"];
                };
            };
        };
    };
    ReactionsController_removeReaction: {
        parameters: {
            query?: never;
            header: {
                /** @description User ID required to remove a reaction */
                userId: string;
            };
            path: {
                /** @description Unique identifier of the item */
                item: string;
                /** @description Type of reaction to remove */
                reactionType: "LOVE" | "FIRE" | "ADMIRE" | "CLAP";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The updated reaction counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReactionResponseDto"];
                };
            };
        };
    };
}
